SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LogHarga](
	[idLog] [int] IDENTITY(201,1) NOT NULL,
	[idAdmin] [varchar](255) NOT NULL,
	[harga] [money] NOT NULL,
	[tanggalBerlaku] [datetime] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LogHarga] ADD  CONSTRAINT [PK_LogHarga] PRIMARY KEY CLUSTERED 
(
	[idLog] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[LogHarga]  WITH CHECK ADD  CONSTRAINT [FK_LogHarga_Admin] FOREIGN KEY([idAdmin])
REFERENCES [dbo].[Admin] ([email])
GO
ALTER TABLE [dbo].[LogHarga] CHECK CONSTRAINT [FK_LogHarga_Admin]
GO
